### ISSUE TITLE
Compatibility issue AutoCAD

### ISSUE THREAD

**Issue by Ximzend** [ThioJoe/ThioJoe-AHK-Scripts#10]
In AutoCAD (I use 2025), when you open the Save window, press the hotkey, and select a path, the path field is populated as expected. However, the drawing still gets saved in the current directory instead of the selected path.

**Comment by ThioJoe** [comment]
Try version 1.2.2, it uses a different method for more modern dialogs. if it still doesn't work can you screenshot what the save/open dialog window looks like for it?

**Comment by Ximzend** [comment]
I have found the problem. AutoCAD opens the Save (As) drawing with the file name selected. When this is the case, it saves the file in the current directory after clicking the path, instead of going to it.
I have attached a screenshot.
![tmp_8d9f0bd7-385c-46f2-9147-875d6a98b633](https://github.com/user-attachments/assets/293912d1-155f-4fa5-9e38-b56e6783ea94)

**Comment by ThioJoe** [comment]
Hm that looks like it might be a custom window. Or fat least using some framework i haven't seen yet. I can look into it

**Comment by ThioJoe** [comment]
Ok it should work now with the latest version 1.2.4
