### ISSUE TITLE
Certain special characters cause errors

### ISSUE THREAD

**Issue by TheGershon** [ThioJoe/ThioJoe-AHK-Scripts#21]
I have a folder that contains the character `&`, EDPS seems to replace it with `&amp;` which results in an error
![image](https://github.com/user-attachments/assets/a1a56d78-fb3c-4fca-b051-fb55cb70d1ef)
I tried a variety of other valid folder name characters and got no errors such as `∶` `~` `!` `√` and `∕` (note that these are all valid unicode characters that are distinct from `:` and `∕`)

**Comment by ThioJoe** [comment]
Huh odd, do you happen to be using directory opus? Seems to happen for that for me but not windows explorer (though the menu still doesn't display & correctly for explorer either, but in a different way - it doesn't show the & at all)

**Comment by ThioJoe** [comment]
Ok should be fixed with the latest v1.2.3.

Ampersands weren't showing at all for regular explorer windows because I forgot to escape them, they're special characters for AHK menus. And for Directory Opus it uses XML so ampersands and apostrophes / single quotes needed to be un-escaped.
