### ISSUE TITLE
[Explorer Dialog Path Selector] Does not run when configured to launch from Task Scheduler

### ISSUE THREAD

**Issue by sjain882** [ThioJoe/ThioJoe-AHK-Scripts#26]
I set up a task scheduler task to start the tool as admin on logon, without a UAC prompt.

This works for almost every program out there. The only exception I've found is HWiNFO64, and this program.

How the task is configured:
<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/069afc68-8668-4d73-a908-3ebeb4f2d44e)

![image](https://github.com/user-attachments/assets/f1bfedb9-ff6c-44df-8645-9b0e16fb0eee)

![image](https://github.com/user-attachments/assets/f242b1b0-44a6-42f0-94ae-0f8a73342e49)

 </details>

But when I right click on task and click Run, nothing happens. The `Last Run Result` is `0x800702E4`.

The program works normally if I launch it normally (as user or admin) from a File Explorer window.

**Comment by sjain882** [comment]
Apologies, it turned out something else was interfering with this tools functionality in elevated applications. The "elevated applications" workaround suggested in the YouTube video now works for me.

**Comment by ThioJoe** [comment]
Ok i'll close this then
